Updated environment variables

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -11,6 +11,11 @@ on:
 permissions:
   contents: read
 
+env:
+  SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
+  SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
+  SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
+
 jobs:
   build:
     runs-on: ubuntu-20.04
@@ -33,6 +38,22 @@ jobs:
       - name: Finalize Build
         run: echo "Build completed successfully!"
 
+      - name: Check Environment Variables
+        run: |
+          if [[ -z "$SPRING_DATASOURCE_URL" ]]; then
+            echo "SPRING_DATASOURCE_URL is not set."
+            exit 1
+          fi
+          if [[ -z "$SPRING_DATASOURCE_USERNAME" ]]; then
+            echo "SPRING_DATASOURCE_USERNAME is not set."
+            exit 1
+          fi
+          if [[ -z "$SPRING_DATASOURCE_PASSWORD" ]]; then
+            echo "SPRING_DATASOURCE_PASSWORD is not set."
+            exit 1
+          fi
+          echo "All required environment variables are set."  
+
   test:
     needs: build
     runs-on: ubuntu-20.04
@@ -51,10 +72,6 @@ jobs:
 
       - name: Run Tests with Gradle
         run: ./gradlew test jacocoTestReport
-        env:
-          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
-          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
-          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
       - name: Finalize Test
         run: echo "Tests completed successfully!"
