Aligned the text in the file

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -16,22 +16,22 @@ jobs:
     runs-on: ubuntu-20.04
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'adopt'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'adopt'
 
-    - name: Make Gradlew Executable
-      run: chmod +x ./gradlew
+      - name: Make Gradlew Executable
+        run: chmod +x ./gradlew
 
-    - name: Build with Gradle
-      run: ./gradlew build --exclude-task test --warning-mode=all
+      - name: Build with Gradle
+        run: ./gradlew build --exclude-task test --warning-mode=all
 
-    - name: Finalize Build
-      run: echo "Build completed successfully!"
+      - name: Finalize Build
+        run: echo "Build completed successfully!"
 
   test:
     needs: build
@@ -43,36 +43,36 @@ jobs:
       DB_USERNAME: ${{ secrets.DB_USERNAME }}
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'adopt'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'adopt'
 
-    - name: Make Gradlew Executable
-      run: chmod +x ./gradlew
+      - name: Make Gradlew Executable
+        run: chmod +x ./gradlew
 
-    - name: Run Tests with Gradle
-      run: ./gradlew test jacocoTestReport
+      - name: Run Tests with Gradle
+        run: ./gradlew test jacocoTestReport
 
-    - name: Finalize Test
-      run: echo "Tests completed successfully!"
+      - name: Finalize Test
+        run: echo "Tests completed successfully!"
 
-    - name: Upload Code Coverage
-      uses: actions/upload-artifact@v2
-      with:
-        name: jacoco-report
-        path: build/reports/jacoco/test/html
+      - name: Upload Code Coverage
+        uses: actions/upload-artifact@v2
+        with:
+          name: jacoco-report
+          path: build/reports/jacoco/test/html
 
-    - name: Check test coverage
-      run: |
-        coverage_percentage=$(grep -Po '(?<=<span class="cover">)[^<]+' build/reports/jacoco/test/html/index.html | tr -d '%')
-        if ((coverage_percentage < 0)); then
-          echo "Error: Code coverage is less than 80%."
-          exit 1
-        fi
-    - name: Finalize Test Coverage
-      run: echo "Test coverage over 80%!"
+      - name: Check test coverage
+        run: |
+          coverage_percentage=$(grep -Po '(?<=<span class="cover">)[^<]+' build/reports/jacoco/test/html/index.html | tr -d '%')
+          if ((coverage_percentage < 0)); then
+            echo "Error: Code coverage is less than 80%."
+            exit 1
+          fi
+      - name: Finalize Test Coverage
+        run: echo "Test coverage over 80%!"
 
